#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INSTALL="$REPO_DIR/install.sh"

source "$SCRIPT_DIR/runner.sh"

TMPDIR_BASE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_BASE"' EXIT

new_target() {
  local dir="$TMPDIR_BASE/$(uuidgen 2>/dev/null || echo $$-$RANDOM)"
  mkdir -p "$dir"
  echo "$dir"
}

# ── --help shows comprehensive help and exits zero ──

echo "install.sh: --help"

output="$(bash "$INSTALL" --help 2>&1)"
result=$({ bash "$INSTALL" --help >/dev/null 2>&1; echo $?; } || echo $?)

assert_eq "exits zero" "0" "$result"
assert_contains "shows usage line" "$output" "Usage:"
assert_contains "describes compose mode" "$output" "Compose"
assert_contains "describes scatter mode" "$output" "Scatter"
assert_contains "shows compose examples" "$output" "my-project code"
assert_contains "shows scatter examples" "$output" "--scatter"
assert_contains "explains subdir:domain format" "$output" "subdir:domain"
assert_contains "lists available domains" "$output" "Available domains:"
assert_contains "lists code domain" "$output" "code"
assert_contains "lists writing domain" "$output" "writing"
assert_contains "documents root-only usage" "$output" "root directives"
assert_contains "documents overwrite behavior" "$output" "overwrite"
assert_contains "mentions no dependencies" "$output" "No dependencies"

# ── No arguments shows usage and exits non-zero ──

echo ""
echo "install.sh: no arguments"

output="$(bash "$INSTALL" 2>&1 || true)"
result=$({ bash "$INSTALL" >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows usage text" "$output" "Usage:"
assert_contains "shows examples" "$output" "Examples:"
assert_contains "lists available domains" "$output" "Available domains:"
assert_eq "exits non-zero" "1" "$result"

# ── Invalid target directory ──

echo ""
echo "install.sh: invalid target directory"

output="$(bash "$INSTALL" /nonexistent/path 2>&1 || true)"
result=$({ bash "$INSTALL" /nonexistent/path >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows error message" "$output" "Error:"
assert_eq "exits non-zero" "1" "$result"

# ── Invalid domain ──

echo ""
echo "install.sh: invalid domain"

target="$(new_target)"
output="$(bash "$INSTALL" "$target" fakeDomain 2>&1 || true)"
result=$({ bash "$INSTALL" "$target" fakeDomain >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows domain error" "$output" "Error:"
assert_contains "suggests available domains" "$output" "Available domains:"
assert_eq "exits non-zero" "1" "$result"

# ── Root-only install ──

echo ""
echo "install.sh: root-only install"

target="$(new_target)"
output="$(bash "$INSTALL" "$target" 2>&1)"
generated="$target/AGENTS.md"

assert_file_exists "creates AGENTS.md" "$generated"
assert_file_not_empty "file is not empty" "$generated"

content="$(cat "$generated")"
assert_contains "has generation comment" "$content" "Generated by agents-md"
assert_contains "includes root content" "$content" "Hierarchy & Inheritance"
assert_contains "includes root enforcement" "$content" "Enforcement"
assert_not_contains "no domain header" "$content" "# Domain:"
assert_contains "stdout confirms install" "$output" "root directives only"

# ── Single domain install ──

echo ""
echo "install.sh: single domain (code)"

target="$(new_target)"
output="$(bash "$INSTALL" "$target" code 2>&1)"
generated="$target/AGENTS.md"

assert_file_exists "creates AGENTS.md" "$generated"

content="$(cat "$generated")"
assert_contains "has generation comment" "$content" "Generated by agents-md"
assert_contains "records domain in comment" "$content" "Domains: code"
assert_contains "includes root content" "$content" "Hierarchy & Inheritance"
assert_contains "includes domain header" "$content" "# Domain: code"
assert_contains "includes domain content" "$content" "RED → GREEN → REFACTOR"
assert_contains "stdout lists root" "$output" "Root directives (always included)"
assert_contains "stdout lists domain" "$output" "✓ code"

# ── Root content appears before domain content ──

echo ""
echo "install.sh: ordering (root before domain)"

target="$(new_target)"
bash "$INSTALL" "$target" code >/dev/null 2>&1
content="$(cat "$target/AGENTS.md")"

root_pos="$(echo "$content" | grep -n "Hierarchy & Inheritance" | head -1 | cut -d: -f1)"
domain_pos="$(echo "$content" | grep -n "# Domain: code" | head -1 | cut -d: -f1)"

assert_eq "root appears before domain" "1" "$([ "$root_pos" -lt "$domain_pos" ] && echo 1 || echo 0)"

# ── Idempotent: running twice overwrites cleanly ──

echo ""
echo "install.sh: idempotent overwrite"

target="$(new_target)"
bash "$INSTALL" "$target" code >/dev/null 2>&1
first_size="$(wc -c < "$target/AGENTS.md" | tr -d ' ')"
bash "$INSTALL" "$target" code >/dev/null 2>&1
second_size="$(wc -c < "$target/AGENTS.md" | tr -d ' ')"

assert_eq "same size after re-run" "$first_size" "$second_size"

# ── Deeply nested domain ──

echo ""
echo "install.sh: deeply nested domain"

nested_dir="$REPO_DIR/deep/nested/domain"
mkdir -p "$nested_dir"
echo "Deep domain rules apply here." > "$nested_dir/AGENTS.md"
trap 'rm -rf "$TMPDIR_BASE" "$REPO_DIR/deep"' EXIT

target="$(new_target)"
output="$(bash "$INSTALL" "$target" deep/nested/domain 2>&1)"
generated="$target/AGENTS.md"

content="$(cat "$generated")"
assert_contains "includes nested domain header" "$content" "# Domain: deep/nested/domain"
assert_contains "includes nested domain content" "$content" "Deep domain rules"
assert_contains "still has root content" "$content" "Hierarchy & Inheritance"

# ── Scatter mode: --scatter places root + subdirectory files ──

echo ""
echo "install.sh --scatter: single domain"

target="$(new_target)"
mkdir -p "$target/src"
output="$(bash "$INSTALL" --scatter "$target" src:code 2>&1)"

assert_file_exists "root AGENTS.md created" "$target/AGENTS.md"
assert_file_exists "subdirectory AGENTS.md created" "$target/src/AGENTS.md"

root_content="$(cat "$target/AGENTS.md")"
assert_contains "root has generation comment" "$root_content" "Generated by agents-md"
assert_contains "root has hierarchy rules" "$root_content" "Hierarchy & Inheritance"
assert_not_contains "root has no domain content" "$root_content" "# Domain:"
assert_not_contains "root has no TDD rules" "$root_content" "RED → GREEN → REFACTOR"

sub_content="$(cat "$target/src/AGENTS.md")"
assert_contains "subdirectory has domain content" "$sub_content" "RED → GREEN → REFACTOR"
assert_not_contains "subdirectory has no root hierarchy" "$sub_content" "Hierarchy & Inheritance"
assert_contains "stdout confirms scatter" "$output" "src:code"

# ── Scatter mode: multiple mappings ──

echo ""
echo "install.sh --scatter: multiple mappings"

target="$(new_target)"
mkdir -p "$target/src" "$target/docs"
output="$(bash "$INSTALL" --scatter "$target" src:code docs:writing 2>&1)"

assert_file_exists "root AGENTS.md created" "$target/AGENTS.md"
assert_file_exists "src AGENTS.md created" "$target/src/AGENTS.md"
assert_file_exists "docs AGENTS.md created" "$target/docs/AGENTS.md"

src_content="$(cat "$target/src/AGENTS.md")"
docs_content="$(cat "$target/docs/AGENTS.md")"
assert_contains "src has code rules" "$src_content" "RED → GREEN → REFACTOR"
assert_not_contains "src has no writing rules" "$src_content" "Purpose Before Prose"
assert_contains "docs has writing rules" "$docs_content" "Purpose Before Prose"
assert_not_contains "docs has no code rules" "$docs_content" "RED → GREEN → REFACTOR"

# ── Scatter mode: creates subdirectory if missing ──

echo ""
echo "install.sh --scatter: creates missing subdirectory"

target="$(new_target)"
output="$(bash "$INSTALL" --scatter "$target" lib:code 2>&1)"

assert_file_exists "created missing subdir AGENTS.md" "$target/lib/AGENTS.md"
assert_file_exists "root still created" "$target/AGENTS.md"

# ── Scatter mode: invalid mapping format ──

echo ""
echo "install.sh --scatter: invalid mapping"

target="$(new_target)"
output="$(bash "$INSTALL" --scatter "$target" badformat 2>&1 || true)"
result=$({ bash "$INSTALL" --scatter "$target" badformat >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows mapping error" "$output" "Error:"
assert_eq "exits non-zero" "1" "$result"

# ── Scatter mode: invalid domain in mapping ──

echo ""
echo "install.sh --scatter: invalid domain in mapping"

target="$(new_target)"
output="$(bash "$INSTALL" --scatter "$target" src:fakeDomain 2>&1 || true)"
result=$({ bash "$INSTALL" --scatter "$target" src:fakeDomain >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows domain error" "$output" "Error:"
assert_eq "exits non-zero" "1" "$result"

# ── Scatter mode: no mappings provided ──

echo ""
echo "install.sh --scatter: no mappings"

target="$(new_target)"
output="$(bash "$INSTALL" --scatter "$target" 2>&1 || true)"
result=$({ bash "$INSTALL" --scatter "$target" >/dev/null 2>&1; echo $?; } || echo $?)

assert_contains "shows error for no mappings" "$output" "Error:"
assert_eq "exits non-zero" "1" "$result"

# ── Scatter mode: nested subdirectory mapping ──

echo ""
echo "install.sh --scatter: nested subdirectory"

target="$(new_target)"
output="$(bash "$INSTALL" --scatter "$target" src/lib/core:code 2>&1)"

assert_file_exists "deeply nested AGENTS.md created" "$target/src/lib/core/AGENTS.md"
assert_file_exists "root still created" "$target/AGENTS.md"

nested_content="$(cat "$target/src/lib/core/AGENTS.md")"
assert_contains "nested has domain content" "$nested_content" "RED → GREEN → REFACTOR"

echo ""
print_results
