#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_AGENTS="$SCRIPT_DIR/AGENTS.md"

print_usage() {
  echo "Usage: ./install.sh <target-directory> [domain ...]"
  echo "       ./install.sh --scatter <target-directory> <subdir:domain> ..."
  echo "       ./install.sh --help"
  echo ""
  echo "Installs an AGENTS.md into your project by composing the root"
  echo "directives with one or more domain-specific directive files."
  echo ""
  echo "Modes:"
  echo "  Compose   Merges root + domains into a single AGENTS.md"
  echo "  Scatter   Places root at project root, each domain in its subdirectory"
  echo ""
  echo "Examples:"
  echo "  ./install.sh ~/my-project code"
  echo "  ./install.sh . code writing"
  echo "  ./install.sh /tmp/project"
  echo "  ./install.sh --scatter ~/my-project src:code docs:writing"
  echo ""
  echo "Available domains:"
  list_domains
}

print_help() {
  print_usage
  echo ""
  echo "Description:"
  echo "  agents-md is a collection of AGENTS.md directive files that shape how"
  echo "  AI agents work on your projects. Each domain encodes a specific workflow"
  echo "  with hard constraints the agent must follow."
  echo ""
  echo "  install.sh composes these directives and places them in your project so"
  echo "  any AI agent that reads AGENTS.md files operates under your rules."
  echo ""
  echo "Compose mode (default):"
  echo "  ./install.sh <target> [domain ...]  Merge root + domains into one file"
  echo ""
  echo "  With no domains, installs root directives only (universal principles"
  echo "  like process-over-output, explicit-over-implicit, earned output)."
  echo "  Use this as a baseline for any project type."
  echo ""
  echo "  With one or more domains, appends each domain's rules after the root"
  echo "  directives. All rules apply everywhere in the project."
  echo ""
  echo "  Examples:"
  echo "    ./install.sh ~/my-project                  root directives only"
  echo "    ./install.sh ~/my-project code              root + code rules"
  echo "    ./install.sh ~/my-project code writing      root + code + writing"
  echo ""
  echo "Scatter mode:"
  echo "  ./install.sh --scatter <target> <subdir:domain> ..."
  echo ""
  echo "  Places root directives at the project root and each domain's rules in"
  echo "  the specified subdirectory. Agents inherit the root principles everywhere"
  echo "  and apply domain rules only within their subdirectory."
  echo ""
  echo "  The subdir:domain format maps a project subdirectory to a domain."
  echo "  Missing subdirectories are created automatically."
  echo ""
  echo "  Examples:"
  echo "    ./install.sh --scatter ~/app src:code docs:writing"
  echo "    ./install.sh --scatter . src/lib:code content/blog:writing"
  echo ""
  echo "Behavior:"
  echo "  - Root directives are always included in every install."
  echo "  - Running install.sh again will overwrite any existing AGENTS.md files."
  echo "  - Generated files include a timestamp comment for traceability."
  echo "  - No dependencies required. Pure bash."
  echo ""
  echo "Testing:"
  echo "  Run ./test.sh to execute the full test suite."
}

list_domains() {
  find "$SCRIPT_DIR" -name "AGENTS.md" -not -path "$ROOT_AGENTS" -print0 \
    | while IFS= read -r -d '' file; do
        local rel="${file#"$SCRIPT_DIR"/}"
        local domain="${rel%/AGENTS.md}"
        local first_line
        first_line="$(head -1 "$file" | sed 's/^#* *//')"
        printf "%s\t%s\n" "$domain" "$first_line"
      done \
    | sort \
    | while IFS=$'\t' read -r domain first_line; do
        printf "  %-20s %s\n" "$domain" "$first_line"
      done
}

validate_target() {
  local target="$1"
  if [ ! -d "$target" ]; then
    echo "Error: Target directory does not exist: $target"
    exit 1
  fi
}

validate_domains() {
  for domain in "$@"; do
    local domain_file="$SCRIPT_DIR/$domain/AGENTS.md"
    if [ ! -f "$domain_file" ]; then
      echo "Error: No AGENTS.md found for domain: $domain"
      echo ""
      echo "Available domains:"
      list_domains
      exit 1
    fi
  done
}

build_agents_file() {
  local target="$1"
  shift
  local domains=("$@")
  local output="$target/AGENTS.md"
  local timestamp
  timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  {
    print_header "$timestamp" "${domains[@]}"
    echo ""
    cat "$ROOT_AGENTS"

    for domain in "${domains[@]}"; do
      append_domain "$domain"
    done
  } > "$output"

  echo "Installed AGENTS.md → $output"
  print_summary "${domains[@]}"
}

print_header() {
  local timestamp="$1"
  shift
  echo "<!-- Generated by agents-md on $timestamp -->"
  echo "<!-- Source: https://github.com/agents-md -->"
  if [ $# -gt 0 ]; then
    echo "<!-- Domains: $* -->"
  fi
}

append_domain() {
  local domain="$1"
  local domain_file="$SCRIPT_DIR/$domain/AGENTS.md"
  echo ""
  echo "---"
  echo ""
  echo "# Domain: $domain"
  echo ""
  cat "$domain_file"
}

print_summary() {
  echo ""
  echo "Composed from:"
  echo "  ✓ Root directives (always included)"
  for domain in "$@"; do
    echo "  ✓ $domain"
  done
}

install_root_only() {
  local target="$1"
  local output="$target/AGENTS.md"
  local timestamp
  timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  {
    print_header "$timestamp"
    echo ""
    cat "$ROOT_AGENTS"
  } > "$output"

  echo "Installed AGENTS.md → $output (root directives only)"
}

validate_mapping_format() {
  local mapping="$1"
  case "$mapping" in
    *:*) return 0 ;;
    *)
      echo "Error: Invalid mapping format '$mapping'. Expected subdir:domain"
      exit 1
      ;;
  esac
}

extract_subdir() {
  echo "${1%%:*}"
}

extract_domain() {
  echo "${1#*:}"
}

validate_mappings() {
  for mapping in "$@"; do
    validate_mapping_format "$mapping"
    local domain
    domain="$(extract_domain "$mapping")"
    local domain_file="$SCRIPT_DIR/$domain/AGENTS.md"
    if [ ! -f "$domain_file" ]; then
      echo "Error: No AGENTS.md found for domain: $domain"
      echo ""
      echo "Available domains:"
      list_domains
      exit 1
    fi
  done
}

install_scatter_domain() {
  local target="$1" subdir="$2" domain="$3"
  local domain_file="$SCRIPT_DIR/$domain/AGENTS.md"
  local output_dir="$target/$subdir"
  mkdir -p "$output_dir"
  cp "$domain_file" "$output_dir/AGENTS.md"
}

scatter_install() {
  local target="$1"
  shift
  local mappings=("$@")

  install_root_only "$target"

  for mapping in "${mappings[@]}"; do
    local subdir domain
    subdir="$(extract_subdir "$mapping")"
    domain="$(extract_domain "$mapping")"
    install_scatter_domain "$target" "$subdir" "$domain"
    echo "  ✓ $subdir:$domain → $target/$subdir/AGENTS.md"
  done
}

main() {
  if [ $# -lt 1 ]; then
    print_usage
    exit 1
  fi

  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    print_help
    return 0
  fi

  if [ "$1" = "--scatter" ]; then
    shift
    run_scatter "$@"
    return
  fi

  local target="$1"
  shift

  validate_target "$target"

  if [ $# -eq 0 ]; then
    install_root_only "$target"
    return
  fi

  validate_domains "$@"
  build_agents_file "$target" "$@"
}

run_scatter() {
  if [ $# -lt 1 ]; then
    print_usage
    exit 1
  fi

  local target="$1"
  shift

  validate_target "$target"

  if [ $# -eq 0 ]; then
    echo "Error: --scatter requires at least one subdir:domain mapping"
    exit 1
  fi

  validate_mappings "$@"
  scatter_install "$target" "$@"
}

main "$@"
